Refine the chapter 2 sentences
Vonng/DDIA pull request #340
Opened 2024-01-05 09:16 UTC by YKIsTheBest

Refine the chapter 2 sentences

2024-01-06 10:34 UTC, yingang requested changes
而 MapReduce 的用途并非专垄于分布式查询执行上。

这一句感觉稍微有点别扭，专垄好像也不是个惯用语，建议改成“而 MapReduce 也并没有垄断所有的分布式查询执行”?

2024-01-06 11:01 UTC, YKIsTheBest commented
> 而 MapReduce 的用途并非专垄于分布式查询执行上。
> 
> 这一句感觉稍微有点别扭，专垄好像也不是个惯用语，建议改成“而 MapReduce 也并没有垄断所有的分布式查询执行”?

Thanks for reviewing , file is updated.

2024-01-07 13:23 UTC, yingang commented
> > 而 MapReduce 的用途并非专垄于分布式查询执行上。
> > 这一句感觉稍微有点别扭，专垄好像也不是个惯用语，建议改成“而 MapReduce 也并没有垄断所有的分布式查询执行”?
> 
> Thanks for reviewing , file is updated.

好的，麻烦也请确认下另外几处建议~

2024-01-07 13:29 UTC, YKIsTheBest commented
> > > 而 MapReduce 的用途并非专垄于分布式查询执行上。
> > > 这一句感觉稍微有点别扭，专垄好像也不是个惯用语，建议改成“而 MapReduce 也并没有垄断所有的分布式查询执行”?
> > 
> > 
> > Thanks for reviewing , file is updated.
> 
> 好的，麻烦也请确认下另外几处建议~

I didnt notice any other advises, can you tell me where it is?
Or, Would you kindly put them in the comment.

Thanks a lot!

2024-01-08 12:14 UTC, yingang commented
> > 好的，麻烦也请确认下另外几处建议~
> 
> I didnt notice any other advises, can you tell me where it is? Or, Would you kindly put them in the comment.
> 
> Thanks a lot!

我也不太熟悉 Github 的 review 机制，你这边看不到类似这样的信息是吧？

![image](https://github.com/Vonng/ddia/assets/1246410/ab9001c9-eb59-48c2-aba7-4b1e89a712e8)

那我先直接贴到这里吧，有三个小点：
1. 即使只访问文档其中的一小部分，数据库通常需要加载整个文档，【这】对于大型文档来说这种加载行为是很浪费的。  -- 建议删除掉前面那个【这】，感觉更通顺一些？
2. 【没有特定的框架须遵守】对 JSON 模型来说往往被认为是一个优势 -- 这里的schema应该是模式而不是框架，建议更新为“无模式对 JSON 模型来说往往被认为是一个优势”？
3. （效果称为尾部延迟放大（tail latency amplification）【24】） -- 括号套括号有点不太好看，建议更新为：（该效果称为尾部延迟放大，即 tail latency amplification【24】）？

2024-01-08 12:39 UTC, YKIsTheBest commented
> > > 好的，麻烦也请确认下另外几处建议~
> > 
> > 
> > I didnt notice any other advises, can you tell me where it is? Or, Would you kindly put them in the comment.
> > Thanks a lot!
> 
> 我也不太熟悉 Github 的 review 机制，你这边看不到类似这样的信息是吧？

Yes, I can't find any below comments, sorry about that.
Maybe I will figure it out sometimes.

> 那我先直接贴到这里吧，有三个小点：
> 
> 1. 即使只访问文档其中的一小部分，数据库通常需要加载整个文档，【这】对于大型文档来说这种加载行为是很浪费的。  -- 建议删除掉前面那个【这】，感觉更通顺一些？
> 2. 【没有特定的框架须遵守】对 JSON 模型来说往往被认为是一个优势 -- 这里的schema应该是模式而不是框架，建议更新为“无模式对 JSON 模型来说往往被认为是一个优势”？
> 3. （效果称为尾部延迟放大（tail latency amplification）【24】） -- 括号套括号有点不太好看，建议更新为：（该效果称为尾部延迟放大，即 tail latency amplification【24】）？

Thanks for reviewing, already modified.

2024-01-09 02:13 UTC, merged

2024-01-09 02:15 UTC, yingang commented
Thanks for your contribution!